name: Deploy to NPM
on:
  push:
    tags:
      - "*"
jobs:
  test:
    name: Run tests and deploy
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "yarn"
      - run: yarn install --prefer-offline --frozen-lockfile
      - run: yarn test
      - run: yarn build
      - run: npm publish
