name: Test and build
on: pull_request
jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - run: yarn test
      - run: yarn build
